//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlotokingNew {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestDataResourceSlotoking {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestDataResourceSlotoking() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlotokingNew.TestDataResourceSlotoking", typeof(TestDataResourceSlotoking).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to djust_test@mail.ru.
        /// </summary>
        internal static string CashLogin {
            get {
                return ResourceManager.GetString("CashLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4012888888881881.
        /// </summary>
        internal static string CreditCardVisa {
            get {
                return ResourceManager.GetString("CreditCardVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +380506452401.
        /// </summary>
        internal static string FacebookLogin {
            get {
                return ResourceManager.GetString("FacebookLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121212qwerty.
        /// </summary>
        internal static string FacebookPass {
            get {
                return ResourceManager.GetString("FacebookPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to djust_test@mail.ru.
        /// </summary>
        internal static string GameUserTest {
            get {
                return ResourceManager.GetString("GameUserTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dijust.test@gmail.com.
        /// </summary>
        internal static string GoogleLogin {
            get {
                return ResourceManager.GetString("GoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qweasdzxcvvv.
        /// </summary>
        internal static string GooglePass {
            get {
                return ResourceManager.GetString("GooglePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dijust.test@mail.ru.
        /// </summary>
        internal static string MailRuLogin {
            get {
                return ResourceManager.GetString("MailRuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qweasdzxcvvv.
        /// </summary>
        internal static string MailRUPass {
            get {
                return ResourceManager.GetString("MailRUPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://slotoking.ntgdev.com/.
        /// </summary>
        internal static string MainPageURL {
            get {
                return ResourceManager.GetString("MainPageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amys1@mail.ru.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ljrkyekgjrhe@mail.ru.
        /// </summary>
        internal static string NewUserWithFS {
            get {
                return ResourceManager.GetString("NewUserWithFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +380506452401.
        /// </summary>
        internal static string OkLogin {
            get {
                return ResourceManager.GetString("OkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121212qwerty.
        /// </summary>
        internal static string OKPass {
            get {
                return ResourceManager.GetString("OKPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 999.
        /// </summary>
        internal static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 380637316714.
        /// </summary>
        internal static string QiwiPhone {
            get {
                return ResourceManager.GetString("QiwiPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestRemindPassword@mail.ru.
        /// </summary>
        internal static string RemindPasswordEmail {
            get {
                return ResourceManager.GetString("RemindPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stage.
        /// </summary>
        internal static string stageLogin {
            get {
                return ResourceManager.GetString("stageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao4F1DAixL7G.
        /// </summary>
        internal static string stagePassword {
            get {
                return ResourceManager.GetString("stagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.petrovskiy@cleack.com.
        /// </summary>
        internal static string TestRestoreUserEmail {
            get {
                return ResourceManager.GetString("TestRestoreUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 506452401.
        /// </summary>
        internal static string TestRestoreUserPhone {
            get {
                return ResourceManager.GetString("TestRestoreUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amys1111@mail.ru.
        /// </summary>
        internal static string TestUserEmail {
            get {
                return ResourceManager.GetString("TestUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.m-y_s@mail.ru.
        /// </summary>
        internal static string TestUserEmailWithSymbols {
            get {
                return ResourceManager.GetString("TestUserEmailWithSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 509991231.
        /// </summary>
        internal static string TestUserPhone {
            get {
                return ResourceManager.GetString("TestUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dijust.test@gmail.com.
        /// </summary>
        internal static string TwitterLogin {
            get {
                return ResourceManager.GetString("TwitterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qweasdzxcvvv.
        /// </summary>
        internal static string TwitterPass {
            get {
                return ResourceManager.GetString("TwitterPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alex.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schicklgruber.
        /// </summary>
        internal static string UserNickname {
            get {
                return ResourceManager.GetString("UserNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adolf.
        /// </summary>
        internal static string UserSurname {
            get {
                return ResourceManager.GetString("UserSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +380506452401.
        /// </summary>
        internal static string VKLogin {
            get {
                return ResourceManager.GetString("VKLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 121212qwerty.
        /// </summary>
        internal static string VKPass {
            get {
                return ResourceManager.GetString("VKPass", resourceCulture);
            }
        }
    }
}
